//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBoyKnowsClass.Hue.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheBoyKnowsClass.Hue.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.meethue.com/api/nupnp.
        /// </summary>
        internal static string BridgeUPNPURI {
            get {
                return ResourceManager.GetString("BridgeUPNPURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/config.
        /// </summary>
        internal static string ConfigURI {
            get {
                return ResourceManager.GetString("ConfigURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api.
        /// </summary>
        internal static string DefaultURI {
            get {
                return ResourceManager.GetString("DefaultURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/groups.
        /// </summary>
        internal static string GroupsAllURI {
            get {
                return ResourceManager.GetString("GroupsAllURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/groups/{2}/action.
        /// </summary>
        internal static string GroupStateURI {
            get {
                return ResourceManager.GetString("GroupStateURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/groups/{2}.
        /// </summary>
        internal static string GroupURI {
            get {
                return ResourceManager.GetString("GroupURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/lights.
        /// </summary>
        internal static string LightsAllURI {
            get {
                return ResourceManager.GetString("LightsAllURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/lights/new.
        /// </summary>
        internal static string LightsNewURI {
            get {
                return ResourceManager.GetString("LightsNewURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/lights/{2}/state.
        /// </summary>
        internal static string LightStateURI {
            get {
                return ResourceManager.GetString("LightStateURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/lights/{2}.
        /// </summary>
        internal static string LightURI {
            get {
                return ResourceManager.GetString("LightURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Collection constructor for type {0}.
        /// </summary>
        internal static string NoCollectionConstructorForType {
            get {
                return ResourceManager.GetString("NoCollectionConstructorForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No object constructor for type {0}.
        /// </summary>
        internal static string NoObjectConstructorForType {
            get {
                return ResourceManager.GetString("NoObjectConstructorForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/schedules.
        /// </summary>
        internal static string SchedulesAllURI {
            get {
                return ResourceManager.GetString("SchedulesAllURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/schedules/{2}.
        /// </summary>
        internal static string ScheduleURI {
            get {
                return ResourceManager.GetString("ScheduleURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}/config/whitelist/{2}.
        /// </summary>
        internal static string UserDeleteURI {
            get {
                return ResourceManager.GetString("UserDeleteURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/api/{1}.
        /// </summary>
        internal static string UserURI {
            get {
                return ResourceManager.GetString("UserURI", resourceCulture);
            }
        }
    }
}
